# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application files from your local machine into the container
COPY . .

# Install required package for system
RUN apt-get update \
   && apt-get upgrade -y \
   && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install mysqlclient
RUN pip install --no-cache-dir -r requirements.txt

# Define the command to run your Flask application
CMD ["python", "app.py"]